// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * AccountCreate
 *
 * 创建账号
 */
export type AccountCreate = {
    /**
     * Account Id
     *
     * 平台账号ID
     */
    account_id: string;
    /**
     * Account Name
     *
     * 账号名称
     */
    account_name: string;
};

/**
 * AccountResponse
 *
 * 账号响应
 */
export type AccountResponse = {
    /**
     * Account Id
     *
     * 平台账号ID
     */
    account_id: string;
    /**
     * Account Name
     *
     * 账号名称
     */
    account_name: string;
    /**
     * Id
     */
    id: number;
    status: AccountStatus;
    /**
     * Last Login
     */
    last_login?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * AccountStats
 *
 * 账号统计
 */
export type AccountStats = {
    /**
     * Total Accounts
     */
    total_accounts: number;
    /**
     * Active Accounts
     */
    active_accounts: number;
    /**
     * Today Published
     */
    today_published?: number;
    /**
     * Total Videos
     */
    total_videos?: number;
};

/**
 * AccountStatus
 */
export type AccountStatus = 'active' | 'inactive' | 'error';

/**
 * AccountUpdate
 *
 * 更新账号
 */
export type AccountUpdate = {
    /**
     * Account Name
     */
    account_name?: string | null;
    status?: AccountStatus | null;
    /**
     * Cookie
     */
    cookie?: string | null;
};

/**
 * AddAudioRequest
 */
export type AddAudioRequest = {
    /**
     * Video Path
     */
    video_path: string;
    /**
     * Audio Path
     */
    audio_path: string;
    /**
     * Output Path
     */
    output_path: string;
    /**
     * Volume
     */
    volume?: number;
};

/**
 * AddCoverRequest
 */
export type AddCoverRequest = {
    /**
     * Video Path
     */
    video_path: string;
    /**
     * Cover Path
     */
    cover_path: string;
    /**
     * Output Path
     */
    output_path: string;
};

/**
 * AutoGenerateRequest
 */
export type AutoGenerateRequest = {
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Count
     */
    count?: number;
};

/**
 * BackupRequest
 *
 * 备份请求
 */
export type BackupRequest = {
    /**
     * Include Logs
     */
    include_logs?: boolean;
};

/**
 * Body_upload_material_api_materials_upload__material_type__post
 */
export type BodyUploadMaterialApiMaterialsUploadMaterialTypePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ClipResultResponse
 */
export type ClipResultResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Output Path
     */
    output_path?: string | null;
    /**
     * Duration
     */
    duration?: number;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * ClipSegmentRequest
 */
export type ClipSegmentRequest = {
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * DetectHighlightsResponse
 */
export type DetectHighlightsResponse = {
    /**
     * Segments
     */
    segments: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Count
     */
    count: number;
};

/**
 * FullPipelineRequest
 */
export type FullPipelineRequest = {
    /**
     * Video Path
     */
    video_path: string;
    /**
     * Audio Path
     */
    audio_path?: string | null;
    /**
     * Cover Path
     */
    cover_path?: string | null;
    /**
     * Target Duration
     */
    target_duration?: number;
    /**
     * Output Dir
     */
    output_dir?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportResponse
 */
export type ImportResponse = {
    /**
     * Success
     */
    success: number;
    /**
     * Failed
     */
    failed: number;
    /**
     * Total
     */
    total: number;
};

/**
 * MaterialCreate
 *
 * 创建素材
 */
export type MaterialCreate = {
    type: MaterialType;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Path
     */
    path?: string | null;
    /**
     * Content
     */
    content?: string | null;
};

/**
 * MaterialListResponse
 *
 * 素材列表响应
 */
export type MaterialListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Items
     */
    items: Array<MaterialResponse>;
};

/**
 * MaterialPathResponse
 */
export type MaterialPathResponse = {
    /**
     * Path
     */
    path: string;
    /**
     * Files
     */
    files: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Type
     */
    type: string;
};

/**
 * MaterialResponse
 *
 * 素材响应
 */
export type MaterialResponse = {
    type: MaterialType;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Path
     */
    path?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Size
     */
    size?: number | null;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MaterialStatsResponse
 */
export type MaterialStatsResponse = {
    /**
     * Video
     */
    video: {
        [key: string]: unknown;
    };
    /**
     * Text
     */
    text: {
        [key: string]: unknown;
    };
    /**
     * Cover
     */
    cover: {
        [key: string]: unknown;
    };
    /**
     * Topic
     */
    topic: {
        [key: string]: unknown;
    };
    /**
     * Audio
     */
    audio: {
        [key: string]: unknown;
    };
};

/**
 * MaterialType
 */
export type MaterialType = 'video' | 'text' | 'cover' | 'topic' | 'audio';

/**
 * MaterialUpdate
 *
 * 更新素材
 */
export type MaterialUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Path
     */
    path?: string | null;
    /**
     * Content
     */
    content?: string | null;
};

/**
 * ProductCreate
 *
 * 创建商品
 */
export type ProductCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Link
     */
    link?: string | null;
};

/**
 * ProductListResponse
 *
 * 商品列表响应
 */
export type ProductListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Items
     */
    items: Array<ProductResponse>;
};

/**
 * ProductResponse
 *
 * 商品响应
 */
export type ProductResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Link
     */
    link?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PublishConfigRequest
 *
 * 发布配置请求
 */
export type PublishConfigRequest = {
    /**
     * Interval Minutes
     */
    interval_minutes?: number;
    /**
     * Start Hour
     */
    start_hour?: number;
    /**
     * End Hour
     */
    end_hour?: number;
    /**
     * Max Per Account Per Day
     */
    max_per_account_per_day?: number;
    /**
     * Shuffle
     */
    shuffle?: boolean;
    /**
     * Auto Start
     */
    auto_start?: boolean;
};

/**
 * PublishConfigResponse
 *
 * 发布配置响应
 */
export type PublishConfigResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Interval Minutes
     */
    interval_minutes: number;
    /**
     * Start Hour
     */
    start_hour: number;
    /**
     * End Hour
     */
    end_hour: number;
    /**
     * Max Per Account Per Day
     */
    max_per_account_per_day: number;
    /**
     * Shuffle
     */
    shuffle: boolean;
    /**
     * Auto Start
     */
    auto_start: boolean;
};

/**
 * PublishControlRequest
 *
 * 发布控制请求
 */
export type PublishControlRequest = {
    /**
     * Action
     *
     * start, pause, stop
     */
    action: string;
};

/**
 * PublishStatus
 */
export type PublishStatus = 'idle' | 'running' | 'paused';

/**
 * PublishStatusResponse
 *
 * 发布状态响应
 */
export type PublishStatusResponse = {
    status: PublishStatus;
    /**
     * Current Task Id
     */
    current_task_id?: number | null;
    /**
     * Total Pending
     */
    total_pending?: number;
    /**
     * Total Success
     */
    total_success?: number;
    /**
     * Total Failed
     */
    total_failed?: number;
};

/**
 * ScanRequest
 */
export type ScanRequest = {
    /**
     * Type
     */
    type?: string | null;
};

/**
 * ScanResponse
 */
export type ScanResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Files
     */
    files: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * SmartClipRequest
 */
export type SmartClipRequest = {
    /**
     * Video Path
     */
    video_path: string;
    /**
     * Segments
     */
    segments: Array<ClipSegmentRequest>;
    /**
     * Output Path
     */
    output_path: string;
    /**
     * Target Duration
     */
    target_duration?: number;
};

/**
 * SystemLogListResponse
 *
 * 系统日志列表响应
 */
export type SystemLogListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Items
     */
    items: Array<SystemLogResponse>;
};

/**
 * SystemLogResponse
 *
 * 系统日志响应
 */
export type SystemLogResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Level
     */
    level: string;
    /**
     * Module
     */
    module?: string | null;
    /**
     * Message
     */
    message: string;
    /**
     * Details
     */
    details?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SystemStats
 *
 * 系统统计
 */
export type SystemStats = {
    /**
     * Total Accounts
     */
    total_accounts: number;
    /**
     * Active Accounts
     */
    active_accounts: number;
    /**
     * Total Tasks
     */
    total_tasks: number;
    /**
     * Pending Tasks
     */
    pending_tasks: number;
    /**
     * Success Tasks
     */
    success_tasks: number;
    /**
     * Failed Tasks
     */
    failed_tasks: number;
    /**
     * Total Products
     */
    total_products: number;
    /**
     * Total Materials
     */
    total_materials: number;
};

/**
 * TaskBatchCreateRequest
 *
 * 批量创建任务
 */
export type TaskBatchCreateRequest = {
    /**
     * Tasks
     */
    tasks: Array<TaskCreate>;
};

/**
 * TaskCreate
 *
 * 创建任务
 */
export type TaskCreate = {
    /**
     * Video Path
     */
    video_path?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Topic
     */
    topic?: string | null;
    /**
     * Cover Path
     */
    cover_path?: string | null;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Material Id
     */
    material_id?: number | null;
};

/**
 * TaskListResponse
 *
 * 任务列表响应
 */
export type TaskListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Items
     */
    items: Array<TaskResponse>;
};

/**
 * TaskResponse
 *
 * 任务响应
 */
export type TaskResponse = {
    /**
     * Video Path
     */
    video_path?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Topic
     */
    topic?: string | null;
    /**
     * Cover Path
     */
    cover_path?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Product Id
     */
    product_id?: number | null;
    status: TaskStatus;
    /**
     * Publish Time
     */
    publish_time?: string | null;
    /**
     * Error Msg
     */
    error_msg?: string | null;
    /**
     * Priority
     */
    priority: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TaskStatsResponse
 */
export type TaskStatsResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Pending
     */
    pending: number;
    /**
     * Running
     */
    running: number;
    /**
     * Success
     */
    success: number;
    /**
     * Failed
     */
    failed: number;
    /**
     * Paused
     */
    paused: number;
    /**
     * Today Success
     */
    today_success: number;
};

/**
 * TaskStatus
 */
export type TaskStatus = 'pending' | 'running' | 'success' | 'failed' | 'paused';

/**
 * TaskUpdate
 *
 * 更新任务
 */
export type TaskUpdate = {
    /**
     * Video Path
     */
    video_path?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Topic
     */
    topic?: string | null;
    /**
     * Cover Path
     */
    cover_path?: string | null;
    /**
     * Account Id
     */
    account_id?: number | null;
    /**
     * Product Id
     */
    product_id?: number | null;
    status?: TaskStatus | null;
    /**
     * Priority
     */
    priority?: number | null;
};

/**
 * TrimVideoRequest
 */
export type TrimVideoRequest = {
    /**
     * Video Path
     */
    video_path: string;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Output Path
     */
    output_path: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VideoInfoResponse
 */
export type VideoInfoResponse = {
    /**
     * Path
     */
    path: string;
    /**
     * Duration
     */
    duration: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
    /**
     * Fps
     */
    fps: number;
    /**
     * Size
     */
    size: number;
    /**
     * Format
     */
    format: string;
};

export type ListAccountsApiAccountsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: string;
    };
    url: '/api/accounts/';
};

export type ListAccountsApiAccountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAccountsApiAccountsGetError = ListAccountsApiAccountsGetErrors[keyof ListAccountsApiAccountsGetErrors];

export type ListAccountsApiAccountsGetResponses = {
    /**
     * Response List Accounts Api Accounts  Get
     *
     * Successful Response
     */
    200: Array<AccountResponse>;
};

export type ListAccountsApiAccountsGetResponse = ListAccountsApiAccountsGetResponses[keyof ListAccountsApiAccountsGetResponses];

export type CreateAccountApiAccountsPostData = {
    body: AccountCreate;
    path?: never;
    query?: never;
    url: '/api/accounts/';
};

export type CreateAccountApiAccountsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAccountApiAccountsPostError = CreateAccountApiAccountsPostErrors[keyof CreateAccountApiAccountsPostErrors];

export type CreateAccountApiAccountsPostResponses = {
    /**
     * Successful Response
     */
    201: AccountResponse;
};

export type CreateAccountApiAccountsPostResponse = CreateAccountApiAccountsPostResponses[keyof CreateAccountApiAccountsPostResponses];

export type GetAccountStatsApiAccountsStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/stats';
};

export type GetAccountStatsApiAccountsStatsGetResponses = {
    /**
     * Successful Response
     */
    200: AccountStats;
};

export type GetAccountStatsApiAccountsStatsGetResponse = GetAccountStatsApiAccountsStatsGetResponses[keyof GetAccountStatsApiAccountsStatsGetResponses];

export type DeleteAccountApiAccountsAccountIdDeleteData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/{account_id}';
};

export type DeleteAccountApiAccountsAccountIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAccountApiAccountsAccountIdDeleteError = DeleteAccountApiAccountsAccountIdDeleteErrors[keyof DeleteAccountApiAccountsAccountIdDeleteErrors];

export type DeleteAccountApiAccountsAccountIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAccountApiAccountsAccountIdDeleteResponse = DeleteAccountApiAccountsAccountIdDeleteResponses[keyof DeleteAccountApiAccountsAccountIdDeleteResponses];

export type GetAccountApiAccountsAccountIdGetData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/{account_id}';
};

export type GetAccountApiAccountsAccountIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAccountApiAccountsAccountIdGetError = GetAccountApiAccountsAccountIdGetErrors[keyof GetAccountApiAccountsAccountIdGetErrors];

export type GetAccountApiAccountsAccountIdGetResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type GetAccountApiAccountsAccountIdGetResponse = GetAccountApiAccountsAccountIdGetResponses[keyof GetAccountApiAccountsAccountIdGetResponses];

export type UpdateAccountApiAccountsAccountIdPutData = {
    body: AccountUpdate;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/{account_id}';
};

export type UpdateAccountApiAccountsAccountIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAccountApiAccountsAccountIdPutError = UpdateAccountApiAccountsAccountIdPutErrors[keyof UpdateAccountApiAccountsAccountIdPutErrors];

export type UpdateAccountApiAccountsAccountIdPutResponses = {
    /**
     * Successful Response
     */
    200: AccountResponse;
};

export type UpdateAccountApiAccountsAccountIdPutResponse = UpdateAccountApiAccountsAccountIdPutResponses[keyof UpdateAccountApiAccountsAccountIdPutResponses];

export type LoginAccountApiAccountsLoginAccountIdPostData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/login/{account_id}';
};

export type LoginAccountApiAccountsLoginAccountIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccountApiAccountsLoginAccountIdPostError = LoginAccountApiAccountsLoginAccountIdPostErrors[keyof LoginAccountApiAccountsLoginAccountIdPostErrors];

export type LoginAccountApiAccountsLoginAccountIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLoginScreenshotApiAccountsLoginAccountIdScreenshotGetData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/login/{account_id}/screenshot';
};

export type GetLoginScreenshotApiAccountsLoginAccountIdScreenshotGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLoginScreenshotApiAccountsLoginAccountIdScreenshotGetError = GetLoginScreenshotApiAccountsLoginAccountIdScreenshotGetErrors[keyof GetLoginScreenshotApiAccountsLoginAccountIdScreenshotGetErrors];

export type GetLoginScreenshotApiAccountsLoginAccountIdScreenshotGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestAccountApiAccountsTestAccountIdPostData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/test/{account_id}';
};

export type TestAccountApiAccountsTestAccountIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestAccountApiAccountsTestAccountIdPostError = TestAccountApiAccountsTestAccountIdPostErrors[keyof TestAccountApiAccountsTestAccountIdPostErrors];

export type TestAccountApiAccountsTestAccountIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutAccountApiAccountsLogoutAccountIdPostData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/logout/{account_id}';
};

export type LogoutAccountApiAccountsLogoutAccountIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutAccountApiAccountsLogoutAccountIdPostError = LogoutAccountApiAccountsLogoutAccountIdPostErrors[keyof LogoutAccountApiAccountsLogoutAccountIdPostErrors];

export type LogoutAccountApiAccountsLogoutAccountIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteAllTasksApiTasksDeleteData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/tasks/';
};

export type DeleteAllTasksApiTasksDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAllTasksApiTasksDeleteError = DeleteAllTasksApiTasksDeleteErrors[keyof DeleteAllTasksApiTasksDeleteErrors];

export type DeleteAllTasksApiTasksDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAllTasksApiTasksDeleteResponse = DeleteAllTasksApiTasksDeleteResponses[keyof DeleteAllTasksApiTasksDeleteResponses];

export type ListTasksApiTasksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: string | null;
        /**
         * Account Id
         */
        account_id?: number | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/tasks/';
};

export type ListTasksApiTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTasksApiTasksGetError = ListTasksApiTasksGetErrors[keyof ListTasksApiTasksGetErrors];

export type ListTasksApiTasksGetResponses = {
    /**
     * Successful Response
     */
    200: TaskListResponse;
};

export type ListTasksApiTasksGetResponse = ListTasksApiTasksGetResponses[keyof ListTasksApiTasksGetResponses];

export type CreateTaskApiTasksPostData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type CreateTaskApiTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskApiTasksPostError = CreateTaskApiTasksPostErrors[keyof CreateTaskApiTasksPostErrors];

export type CreateTaskApiTasksPostResponses = {
    /**
     * Successful Response
     */
    201: TaskResponse;
};

export type CreateTaskApiTasksPostResponse = CreateTaskApiTasksPostResponses[keyof CreateTaskApiTasksPostResponses];

export type GetTaskStatsApiTasksStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/stats';
};

export type GetTaskStatsApiTasksStatsGetResponses = {
    /**
     * Successful Response
     */
    200: TaskStatsResponse;
};

export type GetTaskStatsApiTasksStatsGetResponse = GetTaskStatsApiTasksStatsGetResponses[keyof GetTaskStatsApiTasksStatsGetResponses];

export type DeleteTaskApiTasksTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type DeleteTaskApiTasksTaskIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskApiTasksTaskIdDeleteError = DeleteTaskApiTasksTaskIdDeleteErrors[keyof DeleteTaskApiTasksTaskIdDeleteErrors];

export type DeleteTaskApiTasksTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTaskApiTasksTaskIdDeleteResponse = DeleteTaskApiTasksTaskIdDeleteResponses[keyof DeleteTaskApiTasksTaskIdDeleteResponses];

export type GetTaskApiTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type GetTaskApiTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskApiTasksTaskIdGetError = GetTaskApiTasksTaskIdGetErrors[keyof GetTaskApiTasksTaskIdGetErrors];

export type GetTaskApiTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type GetTaskApiTasksTaskIdGetResponse = GetTaskApiTasksTaskIdGetResponses[keyof GetTaskApiTasksTaskIdGetResponses];

export type UpdateTaskApiTasksTaskIdPutData = {
    body: TaskUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type UpdateTaskApiTasksTaskIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTaskApiTasksTaskIdPutError = UpdateTaskApiTasksTaskIdPutErrors[keyof UpdateTaskApiTasksTaskIdPutErrors];

export type UpdateTaskApiTasksTaskIdPutResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type UpdateTaskApiTasksTaskIdPutResponse = UpdateTaskApiTasksTaskIdPutResponses[keyof UpdateTaskApiTasksTaskIdPutResponses];

export type PublishTaskApiTasksTaskIdPublishPostData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/tasks/{task_id}/publish';
};

export type PublishTaskApiTasksTaskIdPublishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishTaskApiTasksTaskIdPublishPostError = PublishTaskApiTasksTaskIdPublishPostErrors[keyof PublishTaskApiTasksTaskIdPublishPostErrors];

export type PublishTaskApiTasksTaskIdPublishPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BatchCreateTasksApiTasksBatchPostData = {
    body: TaskBatchCreateRequest;
    path?: never;
    query?: never;
    url: '/api/tasks/batch';
};

export type BatchCreateTasksApiTasksBatchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchCreateTasksApiTasksBatchPostError = BatchCreateTasksApiTasksBatchPostErrors[keyof BatchCreateTasksApiTasksBatchPostErrors];

export type BatchCreateTasksApiTasksBatchPostResponses = {
    /**
     * Response Batch Create Tasks Api Tasks Batch Post
     *
     * Successful Response
     */
    201: Array<TaskResponse>;
};

export type BatchCreateTasksApiTasksBatchPostResponse = BatchCreateTasksApiTasksBatchPostResponses[keyof BatchCreateTasksApiTasksBatchPostResponses];

export type AutoGenerateTasksApiTasksAutoGeneratePostData = {
    body: AutoGenerateRequest;
    path?: never;
    query?: never;
    url: '/api/tasks/auto-generate';
};

export type AutoGenerateTasksApiTasksAutoGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AutoGenerateTasksApiTasksAutoGeneratePostError = AutoGenerateTasksApiTasksAutoGeneratePostErrors[keyof AutoGenerateTasksApiTasksAutoGeneratePostErrors];

export type AutoGenerateTasksApiTasksAutoGeneratePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ShuffleTasksApiTasksShufflePostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/shuffle';
};

export type ShuffleTasksApiTasksShufflePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type InitTasksFromMaterialsApiTasksInitFromMaterialsPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Account Id
         */
        account_id: number;
        /**
         * Count
         */
        count?: number;
    };
    url: '/api/tasks/init-from-materials';
};

export type InitTasksFromMaterialsApiTasksInitFromMaterialsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InitTasksFromMaterialsApiTasksInitFromMaterialsPostError = InitTasksFromMaterialsApiTasksInitFromMaterialsPostErrors[keyof InitTasksFromMaterialsApiTasksInitFromMaterialsPostErrors];

export type InitTasksFromMaterialsApiTasksInitFromMaterialsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteAllMaterialsApiMaterialsDeleteData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Type
         */
        type?: string | null;
    };
    url: '/api/materials/';
};

export type DeleteAllMaterialsApiMaterialsDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAllMaterialsApiMaterialsDeleteError = DeleteAllMaterialsApiMaterialsDeleteErrors[keyof DeleteAllMaterialsApiMaterialsDeleteErrors];

export type DeleteAllMaterialsApiMaterialsDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAllMaterialsApiMaterialsDeleteResponse = DeleteAllMaterialsApiMaterialsDeleteResponses[keyof DeleteAllMaterialsApiMaterialsDeleteResponses];

export type ListMaterialsApiMaterialsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Type
         */
        type?: string | null;
    };
    url: '/api/materials/';
};

export type ListMaterialsApiMaterialsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMaterialsApiMaterialsGetError = ListMaterialsApiMaterialsGetErrors[keyof ListMaterialsApiMaterialsGetErrors];

export type ListMaterialsApiMaterialsGetResponses = {
    /**
     * Successful Response
     */
    200: MaterialListResponse;
};

export type ListMaterialsApiMaterialsGetResponse = ListMaterialsApiMaterialsGetResponses[keyof ListMaterialsApiMaterialsGetResponses];

export type CreateMaterialApiMaterialsPostData = {
    body: MaterialCreate;
    path?: never;
    query?: never;
    url: '/api/materials/';
};

export type CreateMaterialApiMaterialsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMaterialApiMaterialsPostError = CreateMaterialApiMaterialsPostErrors[keyof CreateMaterialApiMaterialsPostErrors];

export type CreateMaterialApiMaterialsPostResponses = {
    /**
     * Successful Response
     */
    201: MaterialResponse;
};

export type CreateMaterialApiMaterialsPostResponse = CreateMaterialApiMaterialsPostResponses[keyof CreateMaterialApiMaterialsPostResponses];

export type UploadMaterialApiMaterialsUploadMaterialTypePostData = {
    body: BodyUploadMaterialApiMaterialsUploadMaterialTypePost;
    path: {
        material_type: MaterialType;
    };
    query?: never;
    url: '/api/materials/upload/{material_type}';
};

export type UploadMaterialApiMaterialsUploadMaterialTypePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadMaterialApiMaterialsUploadMaterialTypePostError = UploadMaterialApiMaterialsUploadMaterialTypePostErrors[keyof UploadMaterialApiMaterialsUploadMaterialTypePostErrors];

export type UploadMaterialApiMaterialsUploadMaterialTypePostResponses = {
    /**
     * Successful Response
     */
    200: MaterialResponse;
};

export type UploadMaterialApiMaterialsUploadMaterialTypePostResponse = UploadMaterialApiMaterialsUploadMaterialTypePostResponses[keyof UploadMaterialApiMaterialsUploadMaterialTypePostResponses];

export type GetMaterialStatsApiMaterialsStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/materials/stats';
};

export type GetMaterialStatsApiMaterialsStatsGetResponses = {
    /**
     * Successful Response
     */
    200: MaterialStatsResponse;
};

export type GetMaterialStatsApiMaterialsStatsGetResponse = GetMaterialStatsApiMaterialsStatsGetResponses[keyof GetMaterialStatsApiMaterialsStatsGetResponses];

export type GetMaterialPathApiMaterialsPathMaterialTypeGetData = {
    body?: never;
    path: {
        /**
         * Material Type
         */
        material_type: string;
    };
    query?: never;
    url: '/api/materials/path/{material_type}';
};

export type GetMaterialPathApiMaterialsPathMaterialTypeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMaterialPathApiMaterialsPathMaterialTypeGetError = GetMaterialPathApiMaterialsPathMaterialTypeGetErrors[keyof GetMaterialPathApiMaterialsPathMaterialTypeGetErrors];

export type GetMaterialPathApiMaterialsPathMaterialTypeGetResponses = {
    /**
     * Successful Response
     */
    200: MaterialPathResponse;
};

export type GetMaterialPathApiMaterialsPathMaterialTypeGetResponse = GetMaterialPathApiMaterialsPathMaterialTypeGetResponses[keyof GetMaterialPathApiMaterialsPathMaterialTypeGetResponses];

export type ScanMaterialsApiMaterialsScanPostData = {
    body?: ScanRequest;
    path?: never;
    query?: never;
    url: '/api/materials/scan';
};

export type ScanMaterialsApiMaterialsScanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScanMaterialsApiMaterialsScanPostError = ScanMaterialsApiMaterialsScanPostErrors[keyof ScanMaterialsApiMaterialsScanPostErrors];

export type ScanMaterialsApiMaterialsScanPostResponses = {
    /**
     * Successful Response
     */
    200: ScanResponse;
};

export type ScanMaterialsApiMaterialsScanPostResponse = ScanMaterialsApiMaterialsScanPostResponses[keyof ScanMaterialsApiMaterialsScanPostResponses];

export type ImportMaterialsApiMaterialsImportPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Type
         */
        type?: string | null;
    };
    url: '/api/materials/import';
};

export type ImportMaterialsApiMaterialsImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportMaterialsApiMaterialsImportPostError = ImportMaterialsApiMaterialsImportPostErrors[keyof ImportMaterialsApiMaterialsImportPostErrors];

export type ImportMaterialsApiMaterialsImportPostResponses = {
    /**
     * Successful Response
     */
    200: ImportResponse;
};

export type ImportMaterialsApiMaterialsImportPostResponse = ImportMaterialsApiMaterialsImportPostResponses[keyof ImportMaterialsApiMaterialsImportPostResponses];

export type ImportMaterialsByTypeApiMaterialsImportMaterialTypePostData = {
    body?: never;
    path: {
        /**
         * Material Type
         */
        material_type: string;
    };
    query?: never;
    url: '/api/materials/import/{material_type}';
};

export type ImportMaterialsByTypeApiMaterialsImportMaterialTypePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportMaterialsByTypeApiMaterialsImportMaterialTypePostError = ImportMaterialsByTypeApiMaterialsImportMaterialTypePostErrors[keyof ImportMaterialsByTypeApiMaterialsImportMaterialTypePostErrors];

export type ImportMaterialsByTypeApiMaterialsImportMaterialTypePostResponses = {
    /**
     * Successful Response
     */
    200: ImportResponse;
};

export type ImportMaterialsByTypeApiMaterialsImportMaterialTypePostResponse = ImportMaterialsByTypeApiMaterialsImportMaterialTypePostResponses[keyof ImportMaterialsByTypeApiMaterialsImportMaterialTypePostResponses];

export type DeleteMaterialApiMaterialsMaterialIdDeleteData = {
    body?: never;
    path: {
        /**
         * Material Id
         */
        material_id: number;
    };
    query?: never;
    url: '/api/materials/{material_id}';
};

export type DeleteMaterialApiMaterialsMaterialIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMaterialApiMaterialsMaterialIdDeleteError = DeleteMaterialApiMaterialsMaterialIdDeleteErrors[keyof DeleteMaterialApiMaterialsMaterialIdDeleteErrors];

export type DeleteMaterialApiMaterialsMaterialIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteMaterialApiMaterialsMaterialIdDeleteResponse = DeleteMaterialApiMaterialsMaterialIdDeleteResponses[keyof DeleteMaterialApiMaterialsMaterialIdDeleteResponses];

export type GetMaterialApiMaterialsMaterialIdGetData = {
    body?: never;
    path: {
        /**
         * Material Id
         */
        material_id: number;
    };
    query?: never;
    url: '/api/materials/{material_id}';
};

export type GetMaterialApiMaterialsMaterialIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMaterialApiMaterialsMaterialIdGetError = GetMaterialApiMaterialsMaterialIdGetErrors[keyof GetMaterialApiMaterialsMaterialIdGetErrors];

export type GetMaterialApiMaterialsMaterialIdGetResponses = {
    /**
     * Successful Response
     */
    200: MaterialResponse;
};

export type GetMaterialApiMaterialsMaterialIdGetResponse = GetMaterialApiMaterialsMaterialIdGetResponses[keyof GetMaterialApiMaterialsMaterialIdGetResponses];

export type UpdateMaterialApiMaterialsMaterialIdPutData = {
    body: MaterialUpdate;
    path: {
        /**
         * Material Id
         */
        material_id: number;
    };
    query?: never;
    url: '/api/materials/{material_id}';
};

export type UpdateMaterialApiMaterialsMaterialIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMaterialApiMaterialsMaterialIdPutError = UpdateMaterialApiMaterialsMaterialIdPutErrors[keyof UpdateMaterialApiMaterialsMaterialIdPutErrors];

export type UpdateMaterialApiMaterialsMaterialIdPutResponses = {
    /**
     * Successful Response
     */
    200: MaterialResponse;
};

export type UpdateMaterialApiMaterialsMaterialIdPutResponse = UpdateMaterialApiMaterialsMaterialIdPutResponses[keyof UpdateMaterialApiMaterialsMaterialIdPutResponses];

export type GetMaterialContentApiMaterialsMaterialIdContentGetData = {
    body?: never;
    path: {
        /**
         * Material Id
         */
        material_id: number;
    };
    query?: never;
    url: '/api/materials/{material_id}/content';
};

export type GetMaterialContentApiMaterialsMaterialIdContentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMaterialContentApiMaterialsMaterialIdContentGetError = GetMaterialContentApiMaterialsMaterialIdContentGetErrors[keyof GetMaterialContentApiMaterialsMaterialIdContentGetErrors];

export type GetMaterialContentApiMaterialsMaterialIdContentGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPublishConfigApiPublishConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/publish/config';
};

export type GetPublishConfigApiPublishConfigGetResponses = {
    /**
     * Successful Response
     */
    200: PublishConfigResponse;
};

export type GetPublishConfigApiPublishConfigGetResponse = GetPublishConfigApiPublishConfigGetResponses[keyof GetPublishConfigApiPublishConfigGetResponses];

export type UpdatePublishConfigApiPublishConfigPutData = {
    body: PublishConfigRequest;
    path?: never;
    query?: never;
    url: '/api/publish/config';
};

export type UpdatePublishConfigApiPublishConfigPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePublishConfigApiPublishConfigPutError = UpdatePublishConfigApiPublishConfigPutErrors[keyof UpdatePublishConfigApiPublishConfigPutErrors];

export type UpdatePublishConfigApiPublishConfigPutResponses = {
    /**
     * Successful Response
     */
    200: PublishConfigResponse;
};

export type UpdatePublishConfigApiPublishConfigPutResponse = UpdatePublishConfigApiPublishConfigPutResponses[keyof UpdatePublishConfigApiPublishConfigPutResponses];

export type GetPublishStatusApiPublishStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/publish/status';
};

export type GetPublishStatusApiPublishStatusGetResponses = {
    /**
     * Successful Response
     */
    200: PublishStatusResponse;
};

export type GetPublishStatusApiPublishStatusGetResponse = GetPublishStatusApiPublishStatusGetResponses[keyof GetPublishStatusApiPublishStatusGetResponses];

export type ControlPublishApiPublishControlPostData = {
    body: PublishControlRequest;
    path?: never;
    query?: never;
    url: '/api/publish/control';
};

export type ControlPublishApiPublishControlPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ControlPublishApiPublishControlPostError = ControlPublishApiPublishControlPostErrors[keyof ControlPublishApiPublishControlPostErrors];

export type ControlPublishApiPublishControlPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RefreshDataApiPublishRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/publish/refresh';
};

export type RefreshDataApiPublishRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ShuffleTasksApiPublishShufflePostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/publish/shuffle';
};

export type ShuffleTasksApiPublishShufflePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPublishLogsApiPublishLogsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/publish/logs';
};

export type GetPublishLogsApiPublishLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPublishLogsApiPublishLogsGetError = GetPublishLogsApiPublishLogsGetErrors[keyof GetPublishLogsApiPublishLogsGetErrors];

export type GetPublishLogsApiPublishLogsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSystemStatsApiSystemStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/stats';
};

export type GetSystemStatsApiSystemStatsGetResponses = {
    /**
     * Successful Response
     */
    200: SystemStats;
};

export type GetSystemStatsApiSystemStatsGetResponse = GetSystemStatsApiSystemStatsGetResponses[keyof GetSystemStatsApiSystemStatsGetResponses];

export type GetSystemLogsApiSystemLogsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Level
         */
        level?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/system/logs';
};

export type GetSystemLogsApiSystemLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSystemLogsApiSystemLogsGetError = GetSystemLogsApiSystemLogsGetErrors[keyof GetSystemLogsApiSystemLogsGetErrors];

export type GetSystemLogsApiSystemLogsGetResponses = {
    /**
     * Successful Response
     */
    200: SystemLogListResponse;
};

export type GetSystemLogsApiSystemLogsGetResponse = GetSystemLogsApiSystemLogsGetResponses[keyof GetSystemLogsApiSystemLogsGetResponses];

export type AddSystemLogApiSystemLogsPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Level
         */
        level: string;
        /**
         * Message
         */
        message: string;
        /**
         * Module
         */
        module?: string;
        /**
         * Details
         */
        details?: string;
    };
    url: '/api/system/logs';
};

export type AddSystemLogApiSystemLogsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddSystemLogApiSystemLogsPostError = AddSystemLogApiSystemLogsPostErrors[keyof AddSystemLogApiSystemLogsPostErrors];

export type AddSystemLogApiSystemLogsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSystemConfigApiSystemConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/config';
};

export type GetSystemConfigApiSystemConfigGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateSystemConfigApiSystemConfigPutData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Material Base Path
         */
        material_base_path?: string;
        /**
         * Auto Backup
         */
        auto_backup?: boolean;
        /**
         * Log Level
         */
        log_level?: string;
    };
    url: '/api/system/config';
};

export type UpdateSystemConfigApiSystemConfigPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSystemConfigApiSystemConfigPutError = UpdateSystemConfigApiSystemConfigPutErrors[keyof UpdateSystemConfigApiSystemConfigPutErrors];

export type UpdateSystemConfigApiSystemConfigPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BackupDataApiSystemBackupPostData = {
    body: BackupRequest;
    path?: never;
    query?: never;
    url: '/api/system/backup';
};

export type BackupDataApiSystemBackupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BackupDataApiSystemBackupPostError = BackupDataApiSystemBackupPostErrors[keyof BackupDataApiSystemBackupPostErrors];

export type BackupDataApiSystemBackupPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListProductsApiSystemProductsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/products';
};

export type ListProductsApiSystemProductsGetResponses = {
    /**
     * Successful Response
     */
    200: ProductListResponse;
};

export type ListProductsApiSystemProductsGetResponse = ListProductsApiSystemProductsGetResponses[keyof ListProductsApiSystemProductsGetResponses];

export type CreateProductApiSystemProductsPostData = {
    body: ProductCreate;
    path?: never;
    query?: never;
    url: '/api/system/products';
};

export type CreateProductApiSystemProductsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProductApiSystemProductsPostError = CreateProductApiSystemProductsPostErrors[keyof CreateProductApiSystemProductsPostErrors];

export type CreateProductApiSystemProductsPostResponses = {
    /**
     * Successful Response
     */
    201: ProductResponse;
};

export type CreateProductApiSystemProductsPostResponse = CreateProductApiSystemProductsPostResponses[keyof CreateProductApiSystemProductsPostResponses];

export type DeleteProductApiSystemProductsProductIdDeleteData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/api/system/products/{product_id}';
};

export type DeleteProductApiSystemProductsProductIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProductApiSystemProductsProductIdDeleteError = DeleteProductApiSystemProductsProductIdDeleteErrors[keyof DeleteProductApiSystemProductsProductIdDeleteErrors];

export type DeleteProductApiSystemProductsProductIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProductApiSystemProductsProductIdDeleteResponse = DeleteProductApiSystemProductsProductIdDeleteResponses[keyof DeleteProductApiSystemProductsProductIdDeleteResponses];

export type GetVideoInfoApiAiVideoInfoGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Video Path
         */
        video_path: string;
    };
    url: '/api/ai/video-info';
};

export type GetVideoInfoApiAiVideoInfoGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoInfoApiAiVideoInfoGetError = GetVideoInfoApiAiVideoInfoGetErrors[keyof GetVideoInfoApiAiVideoInfoGetErrors];

export type GetVideoInfoApiAiVideoInfoGetResponses = {
    /**
     * Successful Response
     */
    200: VideoInfoResponse;
};

export type GetVideoInfoApiAiVideoInfoGetResponse = GetVideoInfoApiAiVideoInfoGetResponses[keyof GetVideoInfoApiAiVideoInfoGetResponses];

export type DetectHighlightsApiAiDetectHighlightsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Video Path
         */
        video_path: string;
    };
    url: '/api/ai/detect-highlights';
};

export type DetectHighlightsApiAiDetectHighlightsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DetectHighlightsApiAiDetectHighlightsGetError = DetectHighlightsApiAiDetectHighlightsGetErrors[keyof DetectHighlightsApiAiDetectHighlightsGetErrors];

export type DetectHighlightsApiAiDetectHighlightsGetResponses = {
    /**
     * Successful Response
     */
    200: DetectHighlightsResponse;
};

export type DetectHighlightsApiAiDetectHighlightsGetResponse = DetectHighlightsApiAiDetectHighlightsGetResponses[keyof DetectHighlightsApiAiDetectHighlightsGetResponses];

export type SmartClipApiAiSmartClipPostData = {
    body: SmartClipRequest;
    path?: never;
    query?: never;
    url: '/api/ai/smart-clip';
};

export type SmartClipApiAiSmartClipPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmartClipApiAiSmartClipPostError = SmartClipApiAiSmartClipPostErrors[keyof SmartClipApiAiSmartClipPostErrors];

export type SmartClipApiAiSmartClipPostResponses = {
    /**
     * Successful Response
     */
    200: ClipResultResponse;
};

export type SmartClipApiAiSmartClipPostResponse = SmartClipApiAiSmartClipPostResponses[keyof SmartClipApiAiSmartClipPostResponses];

export type AddAudioApiAiAddAudioPostData = {
    body: AddAudioRequest;
    path?: never;
    query?: never;
    url: '/api/ai/add-audio';
};

export type AddAudioApiAiAddAudioPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddAudioApiAiAddAudioPostError = AddAudioApiAiAddAudioPostErrors[keyof AddAudioApiAiAddAudioPostErrors];

export type AddAudioApiAiAddAudioPostResponses = {
    /**
     * Successful Response
     */
    200: ClipResultResponse;
};

export type AddAudioApiAiAddAudioPostResponse = AddAudioApiAiAddAudioPostResponses[keyof AddAudioApiAiAddAudioPostResponses];

export type AddCoverApiAiAddCoverPostData = {
    body: AddCoverRequest;
    path?: never;
    query?: never;
    url: '/api/ai/add-cover';
};

export type AddCoverApiAiAddCoverPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddCoverApiAiAddCoverPostError = AddCoverApiAiAddCoverPostErrors[keyof AddCoverApiAiAddCoverPostErrors];

export type AddCoverApiAiAddCoverPostResponses = {
    /**
     * Successful Response
     */
    200: ClipResultResponse;
};

export type AddCoverApiAiAddCoverPostResponse = AddCoverApiAiAddCoverPostResponses[keyof AddCoverApiAiAddCoverPostResponses];

export type TrimVideoApiAiTrimPostData = {
    body: TrimVideoRequest;
    path?: never;
    query?: never;
    url: '/api/ai/trim';
};

export type TrimVideoApiAiTrimPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TrimVideoApiAiTrimPostError = TrimVideoApiAiTrimPostErrors[keyof TrimVideoApiAiTrimPostErrors];

export type TrimVideoApiAiTrimPostResponses = {
    /**
     * Successful Response
     */
    200: ClipResultResponse;
};

export type TrimVideoApiAiTrimPostResponse = TrimVideoApiAiTrimPostResponses[keyof TrimVideoApiAiTrimPostResponses];

export type FullPipelineApiAiFullPipelinePostData = {
    body: FullPipelineRequest;
    path?: never;
    query?: never;
    url: '/api/ai/full-pipeline';
};

export type FullPipelineApiAiFullPipelinePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FullPipelineApiAiFullPipelinePostError = FullPipelineApiAiFullPipelinePostErrors[keyof FullPipelineApiAiFullPipelinePostErrors];

export type FullPipelineApiAiFullPipelinePostResponses = {
    /**
     * Successful Response
     */
    200: ClipResultResponse;
};

export type FullPipelineApiAiFullPipelinePostResponse = FullPipelineApiAiFullPipelinePostResponses[keyof FullPipelineApiAiFullPipelinePostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
