import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const frontendRoot = path.resolve(__dirname, '..')
const repoRoot = path.resolve(frontendRoot, '..')

const read = (relativePath) => readFileSync(path.join(repoRoot, relativePath), 'utf8')

const writeIfChanged = (relativePath, content) => {
  const filePath = path.join(repoRoot, relativePath)
  if (readFileSync(filePath, 'utf8') !== content) {
    writeFileSync(filePath, content, 'utf8')
  }
}

const extractCanonicalVersion = () => {
  const backendConfig = read('backend/core/config.py')
  const match = backendConfig.match(/APP_VERSION:\s*str\s*=\s*"([^"]+)"/)
  if (!match) {
    throw new Error('Failed to extract APP_VERSION from backend/core/config.py')
  }

  return match[1]
}

const updateJsonVersion = (relativePath, version) => {
  const filePath = path.join(repoRoot, relativePath)
  const data = JSON.parse(readFileSync(filePath, 'utf8'))
  data.version = version
  writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, 'utf8')
}

const replaceOrThrow = (content, pattern, replacer, description) => {
  if (!pattern.test(content)) {
    throw new Error(`Failed to update ${description}`)
  }

  pattern.lastIndex = 0
  return content.replace(pattern, replacer)
}

const updateLockfileRootVersion = (relativePath, version) => {
  const current = read(relativePath)
  const topLevelUpdated = replaceOrThrow(
    current,
    /("name":\s*"[^"]+",\s*"version":\s*")[^"]+(")/,
    `$1${version}$2`,
    `${relativePath} top-level version`,
  )
  const rootPackageUpdated = replaceOrThrow(
    topLevelUpdated,
    /("packages":\s*{\s*"":\s*{\s*"name":\s*"[^"]+",\s*"version":\s*")[^"]+(")/s,
    `$1${version}$2`,
    `${relativePath} root package version`,
  )
  writeIfChanged(relativePath, rootPackageUpdated)
}

const version = extractCanonicalVersion()

updateJsonVersion('frontend/package.json', version)
updateJsonVersion('frontend/scripts/cli/package.json', version)
updateLockfileRootVersion('frontend/package-lock.json', version)
updateLockfileRootVersion('frontend/scripts/cli/package-lock.json', version)

writeIfChanged(
  'frontend/scripts/cli/src/version.ts',
  `// This file is auto-generated by frontend/scripts/sync-version.mjs\nexport const VERSION = '${version}'\n`,
)

writeIfChanged(
  'README.md',
  replaceOrThrow(
    read('README.md'),
    /^(\*\*版本\*\*:\s*).+$/m,
    `$1${version}`,
    'README version line',
  ),
)

writeIfChanged(
  'docs/epic-7-version-inventory.md',
  replaceOrThrow(
    read('docs/epic-7-version-inventory.md'),
    /(当前 canonical version：\n\n- `)[^`]+(`)/,
    `$1${version}$2`,
    'version inventory canonical version line',
  ),
)

const exportOpenapi = spawnSync('node', ['scripts/export-openapi.mjs'], {
  cwd: frontendRoot,
  stdio: 'inherit',
  shell: false,
})

if ((exportOpenapi.status ?? 1) !== 0) {
  process.exit(exportOpenapi.status ?? 1)
}

console.log(`Synchronized version surfaces to ${version}`)
